### ISSUE TITLE
Header menu not showing

### ISSUE THREAD

**Issue by Sogl** [vmcosta/grav-theme-grayscale#3]
Hello!

With skeleton all works fine.
But after installing theme on fresh `Grav v1.1.0-rc.1` and copy `01.home` directory header menu isn't showing.

How to fix?

**Comment by Sogl** [comment]
Solved by adding in `site.yaml`:

```
# Links to include in navigation
# For external links add external: true
links:
  - title: About
    url: '#about'
  - title: Download
    url: '#download'
  - title: Contact
    url: '#contact'
```
